/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cnf.Telas;

import java.awt.Color;

/**
 *
 * @author kaique.arantes
 */
public class TelaCadastrosPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaCadastrosPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVisualizacao = new javax.swing.JPanel();
        btnVisALunos = new javax.swing.JButton();
        btnVisProfessores = new javax.swing.JButton();
        btnVisFaculdades = new javax.swing.JButton();
        btnVisDisciplinas = new javax.swing.JButton();
        btnVisCNF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelVisualizacao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cadastros e Vizualizações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        btnVisALunos.setText("Alunos");
        btnVisALunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisALunosActionPerformed(evt);
            }
        });

        btnVisProfessores.setText("Professores");
        btnVisProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisProfessoresActionPerformed(evt);
            }
        });

        btnVisFaculdades.setText("Faculdades");
        btnVisFaculdades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisFaculdadesActionPerformed(evt);
            }
        });

        btnVisDisciplinas.setText("Disciplinas");
        btnVisDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisDisciplinasActionPerformed(evt);
            }
        });

        btnVisCNF.setText("Semestre");
        btnVisCNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisCNFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVisualizacaoLayout = new javax.swing.GroupLayout(panelVisualizacao);
        panelVisualizacao.setLayout(panelVisualizacaoLayout);
        panelVisualizacaoLayout.setHorizontalGroup(
            panelVisualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisualizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVisALunos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVisProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVisFaculdades, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVisDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVisCNF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVisualizacaoLayout.setVerticalGroup(
            panelVisualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisualizacaoLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(panelVisualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisALunos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisFaculdades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisCNF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(panelVisualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(panelVisualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisALunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisALunosActionPerformed
        TelaAlunos verAlunos = new TelaAlunos();
        verAlunos.setVisible(true);
        verAlunos.setResizable(false);
        verAlunos.setLocationRelativeTo(null);

        TelaCadastrosPrincipal.this.dispose();
    }//GEN-LAST:event_btnVisALunosActionPerformed

    private void btnVisDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisDisciplinasActionPerformed
        TelaDisciplinas verDisciplinas = new TelaDisciplinas();
        verDisciplinas.setVisible(true);
        verDisciplinas.setResizable(false);
        verDisciplinas.setLocationRelativeTo(null);

        TelaCadastrosPrincipal.this.dispose();
    }//GEN-LAST:event_btnVisDisciplinasActionPerformed

    private void btnVisFaculdadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisFaculdadesActionPerformed
        TelaFaculdades verFaculdades = new TelaFaculdades();
        verFaculdades.setVisible(true);
        verFaculdades.setResizable(false);
        verFaculdades.setLocationRelativeTo(null);

        TelaCadastrosPrincipal.this.dispose();
    }//GEN-LAST:event_btnVisFaculdadesActionPerformed

    private void btnVisProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisProfessoresActionPerformed
        TelaProfessores verProfessores = new TelaProfessores();
        verProfessores.setVisible(true);
        verProfessores.setResizable(false);
        verProfessores.setLocationRelativeTo(null);

        TelaCadastrosPrincipal.this.dispose();
    }//GEN-LAST:event_btnVisProfessoresActionPerformed

    private void btnVisCNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisCNFActionPerformed
        TelaSemestres semestre = new TelaSemestres();
        semestre.setVisible(true);
        semestre.setLocationRelativeTo(null);
        semestre.setResizable(false);

        TelaCadastrosPrincipal.this.dispose();
    }//GEN-LAST:event_btnVisCNFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrosPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrosPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrosPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrosPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
        } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastrosPrincipal principal = new TelaCadastrosPrincipal();
                principal.setResizable(false);
                principal.setVisible(true);
                principal.setLocationRelativeTo(null);
            }
        });
        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisALunos;
    private javax.swing.JButton btnVisCNF;
    private javax.swing.JButton btnVisDisciplinas;
    private javax.swing.JButton btnVisFaculdades;
    private javax.swing.JButton btnVisProfessores;
    private javax.swing.JPanel panelVisualizacao;
    // End of variables declaration//GEN-END:variables
}
